### ISSUE TITLE
Move the rulebook config entry out of the Discord config

### ISSUE THREAD

**Issue by utybo** [EpiLink/EpiLink#192]
It does more than just Discord roles, and should be placed at the root instead.

Before:

```yaml
name: Hello
discord:
  rulebookFile: ...
  ...
```

After:

```yaml
name: Hello
rulebookFile: ...
discord:
  ...
```
